kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      name: frontend
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        resources: {}
        image: hjgraca.azurecr.io/frontend:#{ContainerVersion}#
        env:
        - name: FRONTEND_VERSION
          value: "#{ContainerVersion}#"
        - name: FRONTEND_ENV
          value: "#{Environment}#"
        - name: API_URL
          value: "#{APIUrl}#"
        - name: APPINSIGHTS_INSTRUMENTATIONKEY
          valueFrom:
            secretKeyRef:
              name: appinsightskey
              key: aikey
        terminationMessagePath: "/dev/termination-log"
        terminationMessagePolicy: File
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        securityContext:
          privileged: false
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler